name: Bazel CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md

jobs:

  bazel:
    name: Bazel
    runs-on: ubuntu-latest
    steps:
      - name: Bazel RC
        run: |
          exec > ~/.bazelrc
          echo "common --disk_cache=${{runner.temp}}/bazel.disk --remote_download_outputs=all"
          echo "test --test_output=all"
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{runner.temp}}/bazel.disk
          key: bazel-${{ hashFiles('.bazelignore', '.bazelversion', '.bazelrc', 'WORKSPACE.bazel', 'MODULE.bazel', 'MODULE.bazel.lock', 'maven_install.json') }}
          restore-keys: |
            bazel-
      - name: Bazel Test
        run: bazel test ...
      - uses: actions/upload-artifact@v4
        with:
          name: bazel-testlogs
          path: bazel-testlogs/**